# Generated by Django 6.0 on 2026-01-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('need_institution', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'agent_type',
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'place_type',
            },
        ),
        migrations.CreateModel(
            name='PriorityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'priority_group',
            },
        ),
        migrations.CreateModel(
            name='StatusControl',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('register', 'Registro'), ('validation', 'Validación'), ('goal', 'Objetivo')], default='petition', max_length=10, verbose_name='grupo de status')),
                ('public_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, help_text='https://vuetifyjs.com/en/styles/colors/', max_length=30, null=True)),
                ('icon', models.CharField(blank=True, help_text='https://fonts.google.com/icons', max_length=40, null=True)),
                ('order', models.IntegerField(default=4)),
                ('is_final', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Status de control',
                'verbose_name_plural': 'Status de control (TODOS)',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('is_other', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'topic',
            },
        ),
    ]
