# Generated by Django 6.0 on 2026-01-30 22:34

import django.db.models.deletion
import geo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'health_district',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=2, verbose_name='Clave INEGI')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Corto')),
                ('code_name', models.CharField(blank=True, max_length=6, null=True, verbose_name='Nombre Clave')),
                ('alternative_names', models.JSONField(default=geo.models.default_alternative_names, help_text='Ocupar para OCAMIS', verbose_name='Lista nombres alternativos')),
            ],
            options={
                'verbose_name': 'Entidad Federativa',
                'verbose_name_plural': 'Entidades Federativas',
                'ordering': ['inegi_code'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=6, verbose_name='Clave INEGI')),
                ('complete_code', models.CharField(max_length=8, verbose_name='Clave INEGI Completa')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('std_name', models.CharField(max_length=255, verbose_name='Nombre Estandarizado')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Población')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud de cabecera')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud de cabecera')),
                ('altitude', models.IntegerField(blank=True, null=True, verbose_name='Altitud de cabecera')),
                ('health_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='geo.healthdistrict')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='geo.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['inegi_code'],
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=6, verbose_name='Clave INEGI')),
                ('complete_code', models.CharField(max_length=12, verbose_name='Clave INEGI Completa')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Población')),
                ('is_rural', models.BooleanField(default=False, verbose_name='Es rural')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='geo.municipality', verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.AddField(
            model_name='healthdistrict',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_districts', to='geo.state'),
        ),
    ]
