# Generated by Django 6.0 on 2026-01-30 22:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('men', models.IntegerField(blank=True, null=True)),
                ('women', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asistencia de grupos de edades',
                'verbose_name_plural': 'Asistencias de grupos de edades',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('person_count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Seguimiento a Comunidad',
                'verbose_name_plural': 'Seguimientos a Comunidades',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'goal',
            },
        ),
        migrations.CreateModel(
            name='HealthMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Junta Comunitaria',
                'verbose_name_plural': 'Juntas Comunitarias',
            },
        ),
        migrations.CreateModel(
            name='IntensiveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('person_count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'intensive_day',
            },
        ),
        migrations.CreateModel(
            name='PriorityAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('beneficiaries', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'priority_action',
            },
        ),
        migrations.CreateModel(
            name='ProgressAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'progress_advance',
            },
        ),
        migrations.CreateModel(
            name='TopicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'topic_goal',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('health_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='geo.healthdistrict')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='geo.locality')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='geo.municipality')),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='category.placetype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='geo.state')),
            ],
            options={
                'verbose_name': 'community',
                'verbose_name_plural': 'Communities',
            },
        ),
    ]
