# Generated by Django 6.0 on 2026-01-30 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('gob', '0001_initial'),
        ('plus', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='follow_ups', to='user.agent'),
        ),
        migrations.AddField(
            model_name='followup',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='plus.community'),
        ),
        migrations.AddField(
            model_name='followup',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='follow_ups', to='gob.institution'),
        ),
        migrations.AddField(
            model_name='followup',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='follow_ups_participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='responsible_goals', to='gob.institution'),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='category.statuscontrol'),
        ),
        migrations.AddField(
            model_name='healthmeeting',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='health_meetings', to='user.agent'),
        ),
        migrations.AddField(
            model_name='healthmeeting',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_meetings', to='plus.community'),
        ),
        migrations.AddField(
            model_name='healthmeeting',
            name='conveners',
            field=models.ManyToManyField(blank=True, related_name='convened_meetings', to='gob.institution'),
        ),
        migrations.AddField(
            model_name='healthmeeting',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='health_meetings', to='gob.institution'),
        ),
        migrations.AddField(
            model_name='healthmeeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='health_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthmeeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_meetings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='health_meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='plus.healthmeeting'),
        ),
        migrations.AddField(
            model_name='intensiveday',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='intensive_days', to='user.agent'),
        ),
        migrations.AddField(
            model_name='intensiveday',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='intensive_days', to='plus.community'),
        ),
        migrations.AddField(
            model_name='intensiveday',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='intensive_days', to='gob.institution'),
        ),
        migrations.AddField(
            model_name='intensiveday',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='intensive_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intensiveday',
            name='priority_groups',
            field=models.ManyToManyField(blank=True, related_name='intensive_days', to='category.prioritygroup'),
        ),
        migrations.AddField(
            model_name='intensiveday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intensive_days_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistant',
            name='intensive_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='plus.intensiveday'),
        ),
        migrations.AddField(
            model_name='priorityaction',
            name='intensive_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_actions', to='plus.intensiveday'),
        ),
        migrations.AddField(
            model_name='priorityaction',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_actions', to='gob.program'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='priority_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='plus.priorityaction'),
        ),
        migrations.AddField(
            model_name='progressadvance',
            name='intensive_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_advances', to='plus.intensiveday'),
        ),
        migrations.AddField(
            model_name='progressadvance',
            name='status_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_advances', to='category.statuscontrol'),
        ),
        migrations.AddField(
            model_name='topicgoal',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_goal', to='plus.goal'),
        ),
        migrations.AddField(
            model_name='topicgoal',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_goals', to='category.topic'),
        ),
    ]
